version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Tripti123456
      - MYSQL_DATABASE=fiber_blog
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  blog-app:
    build: .
    container_name: blog-app
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8000:8000"
    environment:
      - db_username=root
      - db_password=Tripti123456
      - db_name=fiber_blog
      - db_host=mysql
      - db_port=3306
    volumes:
      - ./client/build:/var/www/html:ro
    entrypoint: ["/bin/sh", "/startup.sh"]

volumes:
  mysql_data:
